config/routes.rb
Rails.application.routes.draw do
  resources :semesters
  resources :courses
  devise_for :users
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :semester
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :courses
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :semesters

  def username
    email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy]
  before_action :set_semester, only: %i[new edit]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit;end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def set_semester
    @semesters = Semester.all
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def course_params
    params.require(:course).permit(:title, :course_id, :credit, :semester_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
  before_action :set_semester, only: %i[show edit update destroy]

  def index
    @semesters = Semester.all
  end

  def show; end

  def new
    @semester = Semester.new
  end

  def edit; end

  def create
    @semester = Semester.new(semester_params)

    respond_to do |format|
      if @semester.save
        format.html { redirect_to @semester, notice: 'Semester was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @semester.update(semester_params)
        format.html { redirect_to @semester, notice: 'Semester was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @semester.destroy
    respond_to do |format|
      format.html { redirect_to semesters_url, notice: 'Semester was successfully destroyed.' }
    end
  end

  private

  def set_semester
    @semester = Semester.find(params[:id])
  end

  def semester_params
    params.require(:semester).permit(:name, :current, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
  def semester_list_string_to_number
    sem_list_map = [['1-1', 1], ['1-2', 2], ['2-1', 3], ['2-2', 4],
                    ['3-1', 5], ['3-2', 6], ['4-1', 7], ['4-2', 8]]
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/views/courses/_form.html.erb
<%= simple_form_for(@course) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="input-group mb-1 float-left">
      <div class="input-group-prepend">
        <span class="input-group-text" >Course ID<sup><b>*</b></sup></span>
      </div>
      <%= f.input :course_id,
                  label: false,
                  required: true %>
    </div>
    <div class="input-group mb-1">
      <div class="input-group-prepend">
        <span class="input-group-text" >Title<sup><b>*</b></sup> &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;   &nbsp;  &nbsp;</span>
      </div>
      <%= f.input :title,
                  required: true,
                  autofocus: true,
                  label: false %>
    </div>
    <div class="input-group mb-1">
      <div class="input-group-prepend">
        <span class="input-group-text" >Credit<sup><b>*</b></sup> &nbsp; &nbsp;   &nbsp;  &nbsp;</span>
      </div>
      <%= f.input :credit,
                  required: true,
                  autofocus: true,
                  label: false %>
    </div>
    <div class="input-group mb-1">
      <div class="input-group-prepend">
        <span class="input-group-text" >Semester<sup><b>*</b></sup> &nbsp;</span>
      </div>
    <%= f.collection_select :semester_id,
                @semesters, :id, :name,
                prompt: '-----Select A Semester----',
                label: false %>
    </div>
  </div>
<br>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<div id="courses-index" class="container-sm">
  <h1 class="card-header fa fa-align-justify">Courses</h1>
</div>
<hr>
<div class="card container-fluid">
  <table class ="card-body">
    <thead class = "card-header">
      <tr>
        <th>No.</th>
        <th>Course id</th>
        <th>Title</th>
        <th>Credit</th>
        <th>Semester</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
    <% no=0 %>
      <% @courses.each do |course| %>
        <% no=no+1 %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
          <td><%= no %></td>
          <td><%= course.course_id %></td>
          <td><%= course.title %></td>
          <td><%= course.credit %></td>
          <td><%= course.semester %></td>
          <td class="btn-group float-right">
            <%= link_to 'Show', course, class: 'btn btn-sm btn-outline-primary' %>
            <%= link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-outline-success' %>
            <%= link_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br><hr>
  <span class="card-header-actions">
    <%= link_to 'New Course', new_course_path,class: 'btn btn-sm btn-outline-primary' %>
  </span>
  <hr>

</div>

app/views/courses/new.html.erb
<h1 id = "new-course" class="text-center" >New Course</h1>
<hr>

<%= render 'form', course: @course %>
<br>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>Course:</strong>
  <%= @course.course_id %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @course.credit %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @course.semester %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/_alert.html.erb
<% flash.each do |key,value| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="border: solid 1px #222222; border-bottom-left-radius: 20px; border-top-right-radius: 20px">
  <div class="course-reg" style="border: solid 1px #222222; background-color: brown; border-bottom-left-radius: 20px; border-top-right-radius: 20px">
  <a class="navbar-brand" href="<%= root_path %>">&nbsp;    <b>Course Registration</b></a>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">Profile<span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto" >
      <% if current_user %>
        <li class="nav-item dropdown" >
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit Account", edit_user_registration_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to "Sign out", destroy_user_session_path, class: 'dropdown-item',method: :delete %>
          </div>
        </li>
      <% else %>
        <li class = 'nav-item'>
          <%= link_to 'Create Account', new_user_registration_path, class: 'nav-link' %>
        </li>

        <li class = 'nav-item'>
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link'  %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseRegistration</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div align="center" class="container">
      <%= render 'layouts/alert' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome</h1>

app/views/semesters/_form.html.erb
<%= simple_form_for(@semester) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :current %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/semesters/edit.html.erb
<h1>Editing Semester</h1>

<%= render 'form', semester: @semester %>

<%= link_to 'Show', @semester %> |
<%= link_to 'Back', semesters_path %>

app/views/semesters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Semesters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Current</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @semesters.each do |semester| %>
      <tr>
        <td><%= semester.name %></td>
        <td><%= semester.current %></td>
        <td><%= link_to 'Show', semester %></td>
        <td><%= link_to 'Edit', edit_semester_path(semester) %></td>
        <td><%= link_to 'Destroy', semester, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Semester', new_semester_path %>

app/views/semesters/new.html.erb
<h1>New Semester</h1>

<%= render 'form', semester: @semester %>

<%= link_to 'Back', semesters_path %>

app/views/semesters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @semester.name %>
</p>

<p>
  <strong>Current:</strong>
  <%= @semester.current %>
</p>

<%= link_to 'Edit', edit_semester_path(@semester) %> |
<%= link_to 'Back', semesters_path %>